"""GEPA evolution data types."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ExecutionTrajectory:
    """A single agent execution trace for evolution analysis."""
    agent_name: str
    task: str
    tools_used: list[str] = field(default_factory=list)
    tool_count: int = 0
    errors_overcome: int = 0
    total_tokens: int = 0
    success: bool = False
    summary: str = ""
    timestamp: str = ""

    @property
    def qualifies_for_evolution(self) -> bool:
        return self.tool_count >= 5 and self.errors_overcome > 0


@dataclass(frozen=True)
class CandidateSkill:
    """A candidate skill generated by the evolution engine."""
    name: str
    description: str
    triggers: tuple[str, ...] = ()
    prompt_template: str = ""
    source_agent: str = ""
    source_task: str = ""
    estimated_token_savings: int = 0
    generation: int = 1
    score: float = 0.0

    def to_skill_md(self) -> str:
        lines = ["---", f"name: {self.name}", f"description: {self.description}", "triggers:"]
        for t in self.triggers:
            lines.append(f"  - {t}")
        lines.append("---")
        lines.append("")
        lines.append(self.prompt_template)
        return "\n".join(lines)


@dataclass
class EvolutionResult:
    """Result of one evolution cycle."""
    trajectory_id: str = ""
    skills_created: list[CandidateSkill] = field(default_factory=list)
    skills_updated: list[CandidateSkill] = field(default_factory=list)
    status: str = "noop"
    message: str = ""


@dataclass(frozen=True)
class SkillScore:
    """Multi-dimensional score for Pareto selection."""
    skill_name: str
    success_rate: float = 0.0
    token_savings: int = 0
    reuse_count: int = 0
    total_score: float = 0.0
